# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shift_schedule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Console_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Console')),
            ],
        ),
        migrations.CreateModel(
            name='Console_oq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oq_date', models.DateField()),
                ('primary_console', models.BooleanField(default=True)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Console')),
            ],
        ),
        migrations.CreateModel(
            name='Console_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_day', models.BooleanField(default=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('off_schedule_controller', models.BooleanField(default=False)),
                ('date', models.DateField(default=b'2000-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Contoller_shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdate', models.DateField()),
                ('holiday', models.BooleanField(default=False)),
                ('rover', models.BooleanField(default=False)),
                ('meeting', models.BooleanField(default=False)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Console')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Master_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_day', models.BooleanField()),
                ('is_repeating', models.BooleanField(default=True)),
                ('repeat_start', models.DateField(default=b'2017-01-01')),
                ('repeat_interval', models.BigIntegerField(default=28)),
                ('repeat_end', models.DateField(default=b'2099-12-31')),
            ],
        ),
        migrations.CreateModel(
            name='PTO_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField()),
                ('date_pto_taken', models.DateField()),
                ('supervisor_approval', models.BooleanField(default=True)),
                ('manager_approval', models.BooleanField(default=True)),
                ('notes', models.TextField(default=b'')),
                ('type', models.CharField(choices=[(b'PTO', b'Regular PTO'), (b'PTOS', b'Short notice PTO'), (b'J', b'Jury Duty'), (b'B', b'Bereavement'), (b'STD', b'Short Term Disability'), (b'LTD', b'Long Term Disability'), (b'DND', b'Do Not Disurb')], default=b'PTO', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.CharField(max_length=20)),
                ('zero_day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(blank=True, default=b'1950-01-01')),
                ('pto', models.IntegerField(blank=True, default=120)),
                ('phone', models.CharField(blank=True, default=b'', max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=shift_schedule.models.PathAndRename(b'/profile_pictures'))),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.UserProfile')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Shift')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supervisor', to='shift_schedule.UserProfile'),
        ),
        migrations.AddField(
            model_name='pto_table',
            name='coverage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shift_schedule.UserProfile'),
        ),
        migrations.AddField(
            model_name='pto_table',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.UserProfile'),
        ),
        migrations.AddField(
            model_name='master_schedule',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Shift'),
        ),
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Operations_Manager', to='shift_schedule.UserProfile'),
        ),
        migrations.AddField(
            model_name='contoller_shift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.UserProfile'),
        ),
        migrations.AddField(
            model_name='console_schedule',
            name='controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.UserProfile'),
        ),
        migrations.AddField(
            model_name='console_schedule',
            name='deskname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Console'),
        ),
        migrations.AddField(
            model_name='console_schedule',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Shift'),
        ),
        migrations.AddField(
            model_name='console_oq',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.UserProfile'),
        ),
        migrations.AddField(
            model_name='console',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.UserProfile'),
        ),
    ]
