# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-06 17:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Console_oq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oq_date', models.DateField()),
                ('primary_console', models.BooleanField(default=True)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Console')),
            ],
        ),
        migrations.CreateModel(
            name='Console_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_day', models.BooleanField()),
                ('is_holiday', models.BooleanField(default=False)),
                ('off_schedule_controller', models.BooleanField(default=False)),
                ('date', models.DateField(default='2000-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Contoller_shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdate', models.DateField()),
                ('holiday', models.BooleanField(default=False)),
                ('rover', models.BooleanField(default=False)),
                ('meeting', models.BooleanField(default=False)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Console')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Master_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_day', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.CharField(max_length=20)),
                ('zero_day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(blank=True)),
                ('pto', models.IntegerField(blank=True, default=120)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Manager')),
                ('shift', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Shift')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Supervisor'),
        ),
        migrations.AddField(
            model_name='master_schedule',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Shift'),
        ),
        migrations.AddField(
            model_name='contoller_shift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.UserProfile'),
        ),
        migrations.AddField(
            model_name='console_schedule',
            name='controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.UserProfile'),
        ),
        migrations.AddField(
            model_name='console_schedule',
            name='deskname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Console'),
        ),
        migrations.AddField(
            model_name='console_schedule',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Shift'),
        ),
        migrations.AddField(
            model_name='console_oq',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.UserProfile'),
        ),
        migrations.AddField(
            model_name='console',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_schedule.Manager'),
        ),
    ]
